// Regenerate web/js/ltcb.js from the Large Text Compression Benchmark.
//
//   node web/tools/parse-ltcb.mjs
//
// The page is a fixed-column text table inside <pre>, not an HTML <table>, and rows are
// ragged: a program with no enwik8 result leaves that column empty. So the columns come
// from the row of dashes and a number counts only if it ends inside the enwik9 column.
// Counting numbers from the left picks up the wrong one.

import { writeFileSync } from 'fs';

const PAGE = 'https://www.mattmahoney.net/dc/text.html';
const OUT = new URL('../js/ltcb.js', import.meta.url);

const html = await (await fetch(PAGE)).text();

// the first <pre><ol> block is the main ranking; the later ones are "Fails on enwik9"
// and the no-dictionary table, and neither belongs here
const block = html.slice(html.indexOf('<pre><ol>'), html.indexOf('</ol></pre>'));
const lines = block.split('\n');
const strip = (s) => s.replace(/<[^>]*>/g, '').replace(/&amp;/g, '&');

const dashes = lines.find((l) => l.trim().startsWith('-------'));
const groups = [...strip(dashes).matchAll(/-+/g)].map((m) => [m.index, m.index + m[0].length]);
const [lo, hi] = groups[3];   // program, options, enwik8, enwik9

const rows = [];
for (const line of lines) {
  if (!line.startsWith('<li>')) continue;
  const text = strip(line);
  for (const m of text.matchAll(/\d[\d,]*/g)) {
    const end = m.index + m[0].length;
    if (end <= lo - 2 || end > hi + 2) continue;
    const enwik9 = +m[0].replace(/,/g, '');
    if (enwik9 > 1e7) rows.push({ name: text.slice(0, groups[1][0]).trim(), enwik9 });
    break;
  }
}

if (rows.length < 100) throw new Error(`only ${rows.length} rows parsed, the page shape changed`);
rows.sort((a, b) => a.enwik9 - b.enwik9);

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
const today = new Date().toISOString().slice(0, 10);

writeFileSync(OUT, `// Large Text Compression Benchmark: ${PAGE}
// [name, ratio] best first, the ratio being compressed enwik9 over 1e9.
// Generated by web/tools/parse-ltcb.mjs, do not hand-edit. Fetched ${today}.

const ENTRIES = [
${rows.map((r) => `  ['${esc(r.name)}', ${r.enwik9 / 1e9}],`).join('\n')}
];

export const TOTAL = ENTRIES.length;

// Where a ratio would place. Different corpus, so it says which programs compress enwik9
// about as tightly, not that we would score there.
export function rank(cr) {
  let better = 0;
  while (better < TOTAL && ENTRIES[better][1] < cr) better++;
  return { position: better + 1, total: TOTAL, near: ENTRIES[Math.min(better, TOTAL - 1)][0] };
}
`);

console.log(`${rows.length} entries, best ${(rows[0].enwik9 / 1e9).toFixed(4)} (${rows[0].name})`);
console.log(`worst ${(rows.at(-1).enwik9 / 1e9).toFixed(4)} (${rows.at(-1).name})`);
